### ISSUE TITLE
Order Parameters are not sent with /rest/checkout/basketitemslist

### ISSUE THREAD

**Issue by bridges23** [plentymarkets/plenty-cms-library#2]
Order Parameters are not sent with the above mentioned XHR, resulting in 400 (Bad Request). The problem occurs only when Order Parameters are set for the Article. 

Selected Order Parameters in ArticleSingleItemView-Template are not copied into the basketItemList-Object:

`basketItemsList.BasketItemItemID	= parentForm.find('[name="ArticleID"]').val();
            basketItemsList.BasketItemPriceID	= parentForm.find('[name="SYS_P_ID"]').val();
            basketItemsList.BasketItemQuantity	= parentForm.find('[name="ArticleQuantity"]').val();
            basketItemsList.BasketItemBranchID	= parentForm.find('[name="source_category"]').val();`

**Comment by ptopczewski** [comment]
There are no form elements for order parameters in the SingleItemView temlplate.
You have to check the errors in the http-response. If the error stack contains the code 100, you have to load the order parameters form by the rest route "/rest/checkout/container_checkoutorderparamslist/".

With this form, you are able to add the order parameters to your BasketItem object and to process the request again.

Please take a look to the function CheckoutManager.addBasketItem

**Comment by bridges23** [comment]
Hi and thanks for the quick answer. I agree with you. But given the fact that in your documentation suggests to put the OrderParams() into SingleItemView-Template to select them before putting the into the Basket, one would assume that they will be taken over during 'addbasketitems' - this works in the old callisto-template.

**Comment by ptopczewski** [comment]
Hi, you're absolutely right.
We will include a check for existing form elements for order parameters and add them before processing the request.

Thanks!

**Comment by bridges23** [comment]
GREAT!!!

**Comment by bridges23** [comment]
Hi there. Just for planning-purposes: Is there going to be a fix available soon or will this be included in the next template-release? Thanks for the answer!

**Comment by m8n** [comment]
should be fixed
